<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tab_More</name>
   <tag></tag>
   <elementGuidId>bdd01a11-5111-4597-b56d-7c06b0a1115b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div[id*='_wtMoreIcon']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
