<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_AccountTitle</name>
   <tag></tag>
   <elementGuidId>8cfbf807-2910-4257-bb92-c3915d62d34f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[id*='_wtAccountTitle']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
