<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ProductName</name>
   <tag></tag>
   <elementGuidId>b09bfdbc-d6d0-43f6-a7fa-3662ce02f20e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(@id,'_wtPositionListCN')]/div[not(contains(@style,'display:none'))]//input[contains(@id,'_wtProductName')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
