<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_AccountGroup</name>
   <tag></tag>
   <elementGuidId>f085246a-1d1a-4cbd-b235-df61ce286b15</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[id*='_wtAccountGroup']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
