<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>table_OpenCases</name>
   <tag></tag>
   <elementGuidId>26093bc5-b222-4ec7-bdbf-df51b7cdf961</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>table[id*='_wtOpenCases']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
