<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>table_ClosedCases</name>
   <tag></tag>
   <elementGuidId>4e21badd-56b8-4878-bd91-0f0d566c404f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>table[id*='_wtClosedCases']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
