<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_UserName</name>
   <tag></tag>
   <elementGuidId>65d8a1fa-e031-4d15-8ab7-171bf3d54435</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[id*=&quot;wtUserNameInput&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
