<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password</name>
   <tag></tag>
   <elementGuidId>ff530f0d-5f7f-4bf0-96cd-0115c4a3defc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[id*=&quot;wtPasswordInput&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
