<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lbl_FooterText</name>
   <tag></tag>
   <elementGuidId>a31ea825-7647-4ad8-b029-7d2ef6040cd2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div[id*=&quot;wtFooter&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
