<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lbl_Heading</name>
   <tag></tag>
   <elementGuidId>47849c8c-82e5-4c35-91fc-663e36244909</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span[id*=&quot;wtLogoTextString&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
