<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>section_Drawer</name>
   <tag></tag>
   <elementGuidId>991ddc03-13e8-4e3f-b5da-1eb45904a180</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span[id*='_Customer_Tasks']>div[class*='Drawer']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
