<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ReceivedDate</name>
   <tag></tag>
   <elementGuidId>96e9e965-d7ad-4340-b195-59eec75e441d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[id*='_wtstartDate']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
