<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_FileUpload</name>
   <tag></tag>
   <elementGuidId>1084103c-29b0-44a5-bee9-6659e64dff3e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div[id*='_wtDropZone']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
