<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_DocType</name>
   <tag></tag>
   <elementGuidId>1e097557-016d-4d3e-8618-37fbe3b69360</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[id*='_wtdocTypeCombo']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
