<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_AssociateSrPoliticalFigure</name>
   <tag></tag>
   <elementGuidId>ce7d04ef-0a8f-4fd0-92ac-d031a1f67662</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[id*='_wtAssocSrPoiticalFigure']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
