<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>icon_AddNewDocument</name>
   <tag></tag>
   <elementGuidId>9ec16b75-4f97-42a6-8398-1024064e3926</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a[id*='wtAddDoc']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
