<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Back</name>
   <tag></tag>
   <elementGuidId>2449c874-9ae2-4ea6-a863-46a51c994e21</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[value='Back']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
