<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lbl_Recurring</name>
   <tag></tag>
   <elementGuidId>3c6c34da-b9da-44a4-a0e0-4e445ecf691e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@taskblockname='Order']//div[contains(@id,'_wtcontentConfirm')]//label[normalize-space(text())='Recurring']/..</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
