<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>icon_LightningBolt</name>
   <tag></tag>
   <elementGuidId>59ec92a2-a1d5-46d6-a52d-41381d7c5281</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div[id*=&quot;wtimg_CN&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
