<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_FileUpload</name>
   <tag></tag>
   <elementGuidId>44cf85ff-6815-4647-8477-5bd56273b7c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div[id*='_wtDropZone']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
