<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_EndDate</name>
   <tag></tag>
   <elementGuidId>db8b0345-698a-479a-baf3-ead9b2e3d9ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[id*='_wtreceivedDate']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
