<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>section_Body</name>
   <tag></tag>
   <elementGuidId>9298e4df-79b7-451d-9fbd-d5183b6b7988</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div[displayblockname='DOCUMENTS']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
