<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Prefix</name>
   <tag></tag>
   <elementGuidId>cb0f5edd-5c06-47da-84de-998782c1bddb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[id*='_wtBasicInformation'][id*='_wtPrefix']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
