<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>icon_AddNewPhone</name>
   <tag></tag>
   <elementGuidId>a161384f-ee49-4c85-ae27-96b4c369e72f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a[id*='_wtActions_wtAddPhone']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
