<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>table_Phones</name>
   <tag></tag>
   <elementGuidId>6a35b4fd-753f-494e-b695-2cd4e24b0197</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>table[id*='_wtCustomerPhone']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
