<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_FamiliarName</name>
   <tag></tag>
   <elementGuidId>89d528d1-b1ee-4f83-96d1-607cdc87957a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>input[id*='_wtFamiliarName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[id*='_wtFamiliarName']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
