<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_AgeBracket</name>
   <tag></tag>
   <elementGuidId>41decb6a-d78c-49df-b0f2-9e934a36ac98</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[id*='_wtAgeBracket']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
