<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_MaritalStatus</name>
   <tag></tag>
   <elementGuidId>d65cffba-7d44-4f79-bd87-8c60ca71234c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[id*='_wtMaritalStatus']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
