<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>table_Emails</name>
   <tag></tag>
   <elementGuidId>ef8813bf-aa07-4878-bd52-2700079cb2ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>table[id*='_wtCustomerEmail']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
