<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lbl_SectionTitle</name>
   <tag></tag>
   <elementGuidId>7e1cfc27-7df4-4684-97d9-4a0a77cea910</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div[id*='_wtContact'][id*='wtTitle'][class*='CustomPanelExpandable_title']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
