<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>section_Body</name>
   <tag></tag>
   <elementGuidId>e14f0965-530f-4e92-b094-dea3ff66872a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div[displayblockname='NOTES']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
