<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>icon_AddNewDocument</name>
   <tag></tag>
   <elementGuidId>b39fb6d6-579b-462d-974a-01e33a3cf090</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a[id*='_wtUploadDocument']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
