<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>section_Body</name>
   <tag></tag>
   <elementGuidId>30f411f0-72a1-41b8-816a-7976d32db308</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div[displayblockname='DOCUMENTS']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
