<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>table_Documents</name>
   <tag></tag>
   <elementGuidId>1eaeecfc-7297-479a-b8a9-b792a5a31b73</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div[class*='custom-table']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
