<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Tasks</name>
   <tag></tag>
   <elementGuidId>60835fef-8281-4123-9ef3-566f863991d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a[id*='_wtTasksButton']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
