<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>table_Accounts</name>
   <tag></tag>
   <elementGuidId>586857fa-1fc2-4273-8ce0-0dadf3362190</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>table[id*='_wtActiveAccountsTable']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
